<template>
<div class="ticker-wrapper">
<div class="ticker-size-guide">
  <span v-if="longestItem">{{longestItem.text}}</span>
</div>
<div class="ticker-item-location">
  <!--
    The class object here is kind of fun. 'active-ticker-item' is easy to determine, as is 'leaving-ticker-item',
    except when the 
  -->
<div v-for="(item, i) in tickerItems" :key="item.key" 
  :class="{'ticker-item': true, 
  'active-ticker-item': displayingNow == i, 
  'leaving-ticker-item': (displayingNow == i + 1) || (displayingNow == 0 && i == tickerItems.length - 1 && firstCycleCompleted)}" 
  :ref="'ticker' + i">{{item.text}}</div>
</div>

</div>
</template>

<script>
import firebase from "firebase";

export default {
	data() {
		return {
			tickerItems: [],
      displayingNow: 0,
      firstCycleCompleted: false
		};
	},
	mounted() {
		const tickerRef = firebase.database().ref("news-ticker-items");
		this.tickerRef = tickerRef;
		let instance = this;
		tickerRef.once("value").then(function(snap) {
			instance.tickerItems = snap.val();
		});
		setInterval(function() {
			if (instance.displayingNow < instance.tickerItems.length - 1) {
				instance.displayingNow++;
			} else {
        instance.firstCycleCompleted = true
				instance.displayingNow = 0;
			}
		}, 3500);
	},
	computed: {
		longestItem() {
			let tempItems = [...this.tickerItems];
			return tempItems.sort(function(a, b) {
				return b.text.length - a.text.length;
			})[0];
		}
	}
};
</script>

<style scoped>
.ticker-wrapper {
	border-top: 1px solid #aaa;
	border-radius: 10px;
	background: linear-gradient(
		to bottom,
		rgba(0, 0, 0, 0.12) 0%,
		rgba(0, 0, 0, 0.03) 80%
	);
	position: relative;
	padding: 10px;
	padding-right: 0;
	padding-left: 0;
	text-align: center;
	overflow: hidden;
	margin: 0 auto;
	max-width: 750px;
}

.ticker-item {
	box-sizing: border-box;
	display: block;
	font-weight: bold;
	position: absolute;
	text-align: center;
	padding: 6px;
	width: 100%;
	opacity: 0;
	top: 6px;
}

.ticker-size-guide {
	visibility: hidden;
	padding: 6px;
	font-weight: bold;
	pointer-events: none;
}

.active-ticker-item {
	opacity: 1;
	-webkit-animation: slide-in-bottom 0.8s cubic-bezier(0.25, 0.46, 0.45, 0.94)
		both;
	animation: slide-in-bottom 0.8s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
}

.leaving-ticker-item {
	-webkit-animation: slide-out-top 0.8s cubic-bezier(0.55, 0.085, 0.68, 0.53)
		both;
	animation: slide-out-top 0.8s cubic-bezier(0.55, 0.085, 0.68, 0.53) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2017-6-12 18:7:49
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-out-top
 * ----------------------------------------
 */
@-webkit-keyframes slide-out-top {
	0% {
		-webkit-transform: translateY(0);
		transform: translateY(0);
		opacity: 1;
	}
	100% {
		-webkit-transform: translateY(-500px);
		transform: translateY(-500px);
		opacity: 0;
	}
}
@keyframes slide-out-top {
	0% {
		-webkit-transform: translateY(0);
		transform: translateY(0);
		opacity: 1;
	}
	100% {
		-webkit-transform: translateY(-500px);
		transform: translateY(-500px);
		opacity: 0;
	}
}

/**
 * ----------------------------------------
 * animation slide-in-bottom
 * ----------------------------------------
 */

@-webkit-keyframes slide-in-bottom {
	0% {
		-webkit-transform: translateY(100px);
		transform: translateY(100px);
		opacity: 0;
	}
	100% {
		-webkit-transform: translateY(0);
		transform: translateY(0);
		opacity: 1;
	}
}
@keyframes slide-in-bottom {
	0% {
		-webkit-transform: translateY(100px);
		transform: translateY(100px);
		opacity: 0;
	}
	100% {
		-webkit-transform: translateY(0);
		transform: translateY(0);
		opacity: 1;
	}
}
</style>