<template>
  <div>
All items:
{{tickerItems}}
<br><br>

<div class="ticker-wrapper">
<div class="ticker-size-guide">
Longest Item:
  <span v-if="longestItem">{{longestItem.text}}</span>
</div>
<div class="ticker-item-location">
Current Item: <span v-if="tickerItems[0]">{{tickerItems[displayingNow].text}}</span>
</div>
</div>


  </div>
</template>

<script>
  import firebase from "firebase";


  export default {
    data() {
      return {
        tickerItems: [],
        displayingNow: 0

      }
    },
    mounted() {
    const tickerRef = firebase.database().ref("news-ticker-items");
    this.tickerRef = tickerRef;
		let instance = this;
		tickerRef.once("value").then(function(snap) {
			instance.tickerItems = snap.val();
		});
    },
    computed: {
      longestItem(){ 
        let tempItems = [...this.tickerItems]
        return tempItems.sort(function (a, b) { 
          return b.text.length - a.text.length; })[0]
      }
    }
  
  }

//   (function(){
//   var tickerItemLocation = document.querySelector('.ticker-item-location');
//   var tickerItems = ["89¢ Downloads Now Available in Store!", "Ludlow Massacre 100th Anniversary: new video in Media area", "NEW ALBUM \"GHOST LIGHT\" available for pre-order in Store","John's new book, \"Flowers for Sarajevo\" available now in the store","2018 SONGWRITING CAMP REGISTRATION NOW OPEN IN CAMP SECTION", "NEW POST-CHARLOTTESVILLE SONG, \"THE MACHINE,\" FREE DOWNLOAD IN STORE"]
//   var displayingNow = 0;
//   var tickerContent = "";
//   var numberOfItems = tickerItems.length;
//   var tickerSizeGuide = document.querySelector('.ticker-size-guide');
//   var longestItem = tickerItems.sort(function (a, b) { return b.length - a.length; })[0];

//   function populateTicker(){
//     for (var i = 0; i < numberOfItems; i++){
//       tickerContent +=  '<div class="ticker-item" id="ticker' + i + '">' +
//                         tickerItems[i] + '</div>';
//     }
//     tickerItemLocation.innerHTML = tickerContent;
//     document.querySelector('#ticker0').classList.add('active-ticker-item');
//     tickerSizeGuide.innerHTML="<div>" + longestItem + "</div>";
//   }

// function displayTickerItem(){
//   var previouslyActive = document.querySelector('.active-ticker-item') || false;
//    if (previouslyActive){
//     previouslyActive.classList.add('leaving-ticker-item');
//   }

//   setTimeout(function() {
//     document.querySelector('#ticker' + displayingNow).classList.add('active-ticker-item');
//     previouslyActive.classList.remove('active-ticker-item', 'leaving-ticker-item');
//   }, 500);


//   if (displayingNow === numberOfItems - 1){
//     displayingNow = 0;
//   }else {
//     displayingNow++;
//   }
// }

// populateTicker();
// setInterval(displayTickerItem, 4000);
//   })();

</script>

<style scoped>
/* ----------------------------------------------
 * Generated by Animista on 2017-6-12 18:7:49
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-out-top
 * ----------------------------------------
 */
@-webkit-keyframes slide-out-top {
  0% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    opacity: 1;
  }
  100% {
    -webkit-transform: translateY(-500px);
    transform: translateY(-500px);
    opacity: 0;
  }
}
@keyframes slide-out-top {
  0% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    opacity: 1;
  }
  100% {
    -webkit-transform: translateY(-500px);
    transform: translateY(-500px);
    opacity: 0;
  }
}

/**
 * ----------------------------------------
 * animation slide-in-bottom
 * ----------------------------------------
 */

@-webkit-keyframes slide-in-bottom {
  0% {
    -webkit-transform: translateY(100px);
    transform: translateY(100px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    opacity: 1;
  }
}
@keyframes slide-in-bottom {
  0% {
    -webkit-transform: translateY(100px);
    transform: translateY(100px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    opacity: 1;
  }
}
</style>